### ISSUE TITLE
Global config in environment.js?

### ISSUE THREAD

**Issue by mrkongo** [mansona/ember-cli-notifications#101]
Why not config in environment except for the fonts?

Maybe it's useful to have these configurable:

```
autoClear: true,
clearDuration: 3000,
successMessage: 'Something',
includeFontAwesome,
icons,
etc...
```

No?

**Comment by ynnoj** [comment]
@mrkongo I've submitted a provisional PR (#105) that would address this. Please let me know your thoughts.
