### ISSUE TITLE
CSS is affecting other parts of application

### ISSUE THREAD

**Issue by alechirsch** [mansona/ember-cli-notifications#102]
The css from "basscss" does not have a prefix in front of each class name, this is affecting the rest of our applications style significantly.

For example, the classes ".left", ".right", and ".fixed" are applied to every element outside of the notifications component.

**Comment by ynnoj** [comment]
@alechirsch I've just published `4.0.10` which should fix this issue. Thank you for your patience! 🙃

**Comment by alechirsch** [comment]
@ynnoj Awesome! Thanks for putting time into this.
