### ISSUE TITLE
Notification is hidden, class is not set

### ISSUE THREAD

**Issue by owenek1** [mansona/ember-cli-notifications#104]
Hello, 

I have a problem with ember-cli-notifications. I would like to use your addon on my website. I have successfully installed it etc. The problem is when I would like to display a notification. In the application.hbs template I added: {{notification-container position="bottom-right"}}. From a component FAQ I want to call a success notification when user click vote. The FAQ component code is: 
`import Ember from 'ember';

export default Ember.Component.extend({
  i18n: Ember.inject.service('i18n'),
  notifications: Ember.inject.service('notification-messages'),

  //Question
  faq: null,

  //Voted status
  hasVoted: false,

  actions: {
    helpful: function() {
      // TODO:
      this.get('notifications').error('Something went wrong');
      this.set('hasVoted', true);
    }
  }
});`

Now what happens is that the notification is inserted into the HTML code but the class of the notification is not being added. The html code of the notification is: 
`<div role="alert" class="alert alert-icon  alert-" style="display: none;">
  <strong></strong> 
</div>`

As you can see the alert-danger class is not added and instead of it I have alert- and also the style is to display: none; so the notification is not going to be displayed. 

Do you know what am I doing wrong? 

Thanks for your help!

**Comment by ynnoj** [comment]
@owenek1 Are you able to provide a app demonstrating this problem? I'm struggling to replicate this issue, and the markup you've highlighted is not a part of this add-on 😕

**Comment by ynnoj** [comment]
Closing. Please re-open if you're still having problems.
