### ISSUE TITLE
Setting a global default value

### ISSUE THREAD

**Issue by rinoldsimon** [mansona/ember-cli-notifications#106]
Where do i need to set a global default value in my application ?
For eg: Where do i set this ~ `this.get('notifications').setDefaultAutoClear(true);` ?

**Comment by ynnoj** [comment]
@rinoldsimon You can set the global values in anywhere the `notification-messages` service is injected. Normally this would be the `application` controller or route.

There is an open PR (#105) that changes this behaviour, meaning the user would define these globals in their application's config.

``` js
var ENV = {
  'ember-cli-notifications': {
      includeFontAwesome: true,
      autoClear: true,
      clearDuration: 5000
  }
}
```

Please re-open if you have any further questions 🙃
