### ISSUE TITLE
Dismissing autoclosing notifications

### ISSUE THREAD

**Issue by lolmaus** [mansona/ember-cli-notifications#11]
Is there a particular reason why autoclosing notifications lack a dismiss button?

Is there a reason why a tiny button is used to close a notification?

I believe that all notifications should be dismissable. And they should be dismissed by clicking anywhere on the notification slate. A close button could display on hover over the slate.

If you agree, i can send a PR.

**Comment by mansona** [comment]
I'm not sure clicking on them anywhere to dismiss them is a good idea from a UX perspective, especially if you need to hover over them to view the x

I like the fact that there is an x for discoverability i.e. the user knows that they can be closed. Maybe we should design a larger touch surface though in the case that someone is viewing these on a mobile device. how about a section at the end of the "slate" became a close? 

I agree that you should be able to dismiss the auto-closing notifications.

**Comment by griffind** [comment]
I have also seen users try and click the wrong x on error messages.

**Comment by ynnoj** [comment]
Not sure about the legitimacy of clicking anywhere on the message to dismiss. In some instances, these notifications could be interactive (link, button) or include information that may needed to be copied the in the case of a fatal error.

I'm happy to accept a PR that enables the currently implemented dismiss for ALL notifications, regardless of auto clear or not.

**Comment by ynnoj** [comment]
@griffind That's a good point. We should probably look for an alternative to represent an error message. Again, happy to accept a PR.
