### ISSUE TITLE
Github page appears to be out of date

### ISSUE THREAD

**Issue by Matt-Jensen** [mansona/ember-cli-notifications#110]
[Github page](http://stonecircle.github.io/ember-cli-notifications/)
![image](https://cloud.githubusercontent.com/assets/1538209/19412196/1d035e62-92d6-11e6-8304-71c68c044897.png)

Local build:
![image](https://cloud.githubusercontent.com/assets/1538209/19412202/52e6cf0a-92d6-11e6-9a42-b48448562867.png)

**Comment by ynnoj** [comment]
Haven't updated the demo page yet as I've yet to publish a release that includes those changes 😁
