### ISSUE TITLE
Ember Warning: Binding style attributes

### ISSUE THREAD

**Issue by alechirsch** [mansona/ember-cli-notifications#114]
In version 4.0.10 I am getting a Warning in the console whenever a notification pops up.

WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.

This is possibly because of line 15 in addon/templates/components/notification-message.hbs

<div local-class="c-notification__countdown" style="{{notificationClearDuration}}"></div>

**Comment by ynnoj** [comment]
@alechirsch `4.0.11` will fix this 🙃
