### ISSUE TITLE
No class in container div after upgrading to ember-cli v2.10.0

### ISSUE THREAD

**Issue by vsymguysung** [mansona/ember-cli-notifications#127]
After upgrading ember-cli to v2.10.0, I found that the container div doesn't include `_c-notification__container--*` class anymore so no style gets applied.
I tested and confirmed this with a barebone ember-cli project with this addon.

**Comment by vsymguysung** [comment]
It looks `localClassNameBindings` in the `notification-container` component is not working properly with ember-cli v2.10.0.
Neither `processedType` nor `computedPosition` is working after upgrading ember-cli up to date.
Any idea ? 
Thanks.

**Comment by vsymguysung** [comment]
Is this issue related with https://github.com/salsify/ember-css-modules/issues/56 ?

**Comment by James1x0** [comment]
Also having this issue on a new project, but not an existing project after upgrading to ember/emcli@2.10.x

**Comment by nmcclay** [comment]
+1 on this, was really caught be surprise that this stopped working.

**Comment by ynnoj** [comment]
This should be fixed in `4.1.3` which I just published.

The guilty lines have been present since [4.0.10](https://github.com/stonecircle/ember-cli-notifications/releases/tag/v4.0.10). I think updating to `ember-cli@2.10.0` (which includes `npm` 3) has resorted in some dependency churn.

Hopefully your issues are fixed 🙃

**Comment by vsymguysung** [comment]
Awesome! thanks much!!! 👍

**Comment by vsymguysung** [comment]
@ynnoj :  Could you please run `npm publish` ? NPM is still pointing v4.1.1. Thanks in advance.

**Comment by ynnoj** [comment]
@vsymguysung Oops, published! I should probably get Travis to automate that.

**Comment by vsymguysung** [comment]
👍
