### ISSUE TITLE
Automate version publishing with Travis

### ISSUE THREAD

**Issue by ynnoj** [mansona/ember-cli-notifications#129]

**Comment by mansona** [comment]
Do you know how you're going to do this? I may have a nice way to set this up for you 👍

**Comment by ynnoj** [comment]
@mansona https://github.com/semantic-release/semantic-release

Been using it on a couple of personal packages and at Moltin. Works nicely.

**Comment by mansona** [comment]
wow... I'll have to take a look at this 🎉  @aklkv you might want to check it out too
