### ISSUE TITLE
postcss-cssnext dependency missing

### ISSUE THREAD

**Issue by ynnoj** [mansona/ember-cli-notifications#131]

**Comment by job13er** [comment]
It looks like [this commit](https://github.com/stonecircle/ember-cli-notifications/commit/43ee13bbec02190ed8076a5d2b4dd11880076e9f) moved the dependency from `dependencies` to `devDependencies` but it's still being required [here](https://github.com/stonecircle/ember-cli-notifications/blob/master/index.js#L13)

**Comment by ynnoj** [comment]
@job13er Yeah I'll get a patch out tonight. My bad.

**Comment by ynnoj** [comment]
`4.1.4` fixes this.
