### ISSUE TITLE
Eliminate Deprecation Warning: Add isServiceFactory: true to notification-messages-service

### ISSUE THREAD

**Issue by joelpresence** [mansona/ember-cli-notifications#133]
Hi,

Awesome addon, thanks so much for making this available!

When I use this addon in Ember 2.9.0, I get the following warning:
```
ember.debug.js:6628 DEPRECATION: In Ember 2.0 service factories must have
an `isServiceFactory` property set to true. You registered (subclass of Ember.ArrayProxy)
as a service factory. Either add the `isServiceFactory` property to this factory or extend
from Ember.Service. [deprecation id: ember-application.validate-type]
```

I am extending your base service with my own as suggested in the README:
```
// In my own own app/services/notifications.js
import NotificationsService from 'ember-cli-notifications/services/notification-messages-service';

export default NotificationsService.extend({
// ...
});
```

I believe this library causes the deprecation warning in [https://github.com/stonecircle/ember-cli-notifications/blob/master/addon/services/notification-messages-service.js](notification-messages-service) where it extends `Ember.ArrayProxy`.  Could you add a line like the following to this class so that users of this addon don't need to:
```
  isServiceFactory: true,
  // Rest of the properties ...
```
I could add this to my service when it extends yours, but that would mean that everybody who extends the base service will need to make this change.  Why not include it in the base class?  :-)

Thanks again!

**Comment by ynnoj** [comment]
Fixed by #142.
