### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by ad-lebedev** [mansona/ember-cli-notifications#137]
Hi! Happy New Year ;)
I found an error in the documentation: your example uses incorrect method name on [this](http://stonecircle.github.io/ember-cli-notifications/) page in the "Clear Duration" section.
I think it must be:
```javascript
this.get('notifications').setDefaultClearDuration(1200);
```
not  
```javascript
this.get('notifications'). setDefaultClearNotification(1200);
```
Thanks for your work, package is really wonderful!

**Comment by ynnoj** [comment]
@ad-lebedev This has now been fixed. Thanks 🙃
