### ISSUE TITLE
Ability to specify icon classes

### ISSUE THREAD

**Issue by adamlc** [mansona/ember-cli-notifications#145]
It will be great to be able to specify the classes for icons. We use [semantic-ui](http://semantic-ui.com/elements/icon.html). I see you can specify an "icons" variable, maybe we could have an iconClasses option like this?

```javascript
'ember-cli-notifications': {
  iconClasses: {
    info: "glyphicon glyphicon-info-sign",
    ..... etc
  }
}
```

**Comment by mansona** [comment]
We no longer support changing the icon set at build time now that https://github.com/mansona/ember-cli-notifications/pull/251 has been released. We have simplified the CSS stack so it should be possible to override the icons using CSS 🤔 let me know if you have any questions or would like to open this issue again 👍
