### ISSUE TITLE
Minified styles cause notifications styling to not work

### ISSUE THREAD

**Issue by SenhorLion** [mansona/ember-cli-notifications#146]
Using `"ember-cli-notifications": "4.1.6"` when using minified CSS the notifications don't have styling, they still function but they are not styled? I updated from `4.0.12` as I thought maybe there could have been an issue but the same behaviour is happening.

**Comment by krachtstefan** [comment]
Hi @SenhorLion, I started to use this addon today and just made a quick deploy to see if I may have similar CSS issues, but it looks fine though.

**Comment by ynnoj** [comment]
I'm going to go ahead and close this issue. Please reopen if you're still encountering issues.
