### ISSUE TITLE
Fastboot support

### ISSUE THREAD

**Issue by drauschenbach** [mansona/ember-cli-notifications#150]
This plugin throws exceptions due to a missing DOM, when Ember Fastboot is used.

A great first step would be to gracefully do nothing, so that Fastboot projects could use this plugin.

**Comment by drauschenbach** [comment]
I'm having trouble reproducing this problem now. I may have been observing an error coming from another plugin.

**Comment by ynnoj** [comment]
Closing. Please re-open if this issue resurfaces.
