### ISSUE TITLE
Breaking error

### ISSUE THREAD

**Issue by jakeleboeuf** [mansona/ember-cli-notifications#156]
Followed steps in documentation, and getting this error:

> Error: Could not find module `ember-cli-notifications/styles/components/notification-container` imported from `ember-cli-notifications/components/notification-container`

**Comment by jakeleboeuf** [comment]
Thinking this is somehow related to a `postcss-import` conflict?

**Comment by ynnoj** [comment]
@jakeleboeuf Sounds like `ember-css-modules` is missing from your app. It _should_ be installed be as a dependency by this add-on. `postcss-import` is only used for the demo.

Can you check?
```bash
npm ls ember-css-modules
```

**Comment by ynnoj** [comment]
Going to close this, please re-open if you're still having issues.
