### ISSUE TITLE
Use YUIDoc for docs reference

### ISSUE THREAD

**Issue by ynnoj** [mansona/ember-cli-notifications#164]
https://github.com/cibernox/ember-cli-yuidoc

**Comment by mansona** [comment]
You might want to checkout https://github.com/ember-learn/ember-cli-addon-docs

It was discussed here: https://player.fm/series/the-embermap-podcast/photo-uploads-server-errors-in-ember-data-npm-dependencies-and-ember-cli-addon-docs

**Comment by mansona** [comment]
👋 @ynnoj 😂

**Comment by ynnoj** [comment]
@mansona tired of seeing this in my issues 😆
