### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by jackmatt2** [mansona/ember-cli-notifications#17]
README.md says to put the following into your template

```
<div class="notifications-container">
    {{#each notification in notifications}}
        {{notification-message notification=this}}
    {{/each}}
</div>
```

should be the following as the above does not work in the latest ember

```
<div class="notifications-container">
    {{#each notification in notifications}}
        {{notification-message notification=notification}}
    {{/each}}
</div>
```

**Comment by ynnoj** [comment]
I'll be doing a release over the weekend that'll include the fix @lolmaus pushed for this [#13](https://github.com/Blooie/ember-cli-notifications/pull/13). I'll be sure to update the docs :)
