### ISSUE TITLE
Add option to specify the fade-out animation

### ISSUE THREAD

**Issue by rodrigomf24** [mansona/ember-cli-notifications#172]
I was trying to make the fade-out animation not too playful (I love the way it works by default, but I was required to make it more subtle). It would be great to add animation options for when the notification shows and hides. I tried adding classes and overriding the animations but I had no success.

**Comment by mansona** [comment]
@rodrigomf24 I don't know if this is still an issue for you but could you let me know if https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 solves your issue? Essentially we are no longer using Component CSS so it is much easier to override any styles (assuming the animations too).

**Comment by mansona** [comment]
I'm closing this now that https://github.com/mansona/ember-cli-notifications/pull/251 is merged and it should allow you to override CSS more effectively. Let me know if you have any more questions 👍
