### ISSUE TITLE
clicking the close/cancel icon triggers the callback

### ISSUE THREAD

**Issue by jondayton** [mansona/ember-cli-notifications#176]
When clicking on the close icon, the onClick callback will be triggered if defined. This seems counterintuitive, as the design and placement makes it should close or cancel the action. It's leading to some strange behavior in our application, where people who are trying to dismiss a link to a page update are instead taken to that page.

detailed here in a PR that seems to have been closed:
https://github.com/stonecircle/ember-cli-notifications/pull/79
Another potential solution is to pass either the event itself or a param that denotes whether or not it was a "dismiss" action, and the result can be handled in the `onClick` callback itself:
https://github.com/stonecircle/ember-cli-notifications/pull/135

Any plans on incorporating this?

**Comment by marxsk** [comment]
I have prepared a patch based on #79 but it is based on the top of my refactored version #190. So I have to wait if it will be approved before next PR. For now, feel free to use my branch:

https://github.com/marxsk/ember-cli-notifications/tree/onClose

**Comment by basz** [comment]
@marxsk would be great if we could still get this behaviour even when it looks like #79 won't get merged...

**Comment by lougreenwood** [comment]
I just stumbled across this issue too...

**Comment by mansona** [comment]
Hey folks 👋 thanks for the issue report, and yes I think it's very counterintuitive 🙈 

I have fixed it in https://github.com/mansona/ember-cli-notifications/pull/259 so if someone has a chance to review the PR that would be much appreciated and we could get this fixed 🎉

**Comment by mansona** [comment]
Hi, it's me again 👋 

I was able to recreate this behaviour in a test, and was able to put together a fix. But it turned out that really early versions of Ember were causing the test system a bit of trouble so I had to drop some support and release a 6.0 version of the addon.

Let me know if it fixes your issue 👍
