### ISSUE TITLE
Font Awesome icons and css issue

### ISSUE THREAD

**Issue by jackmatt2** [mansona/ember-cli-notifications#18]
I have already imported these into my project. 

I got an error that said I needed to add `{overwrite : true}` to mergeTrees for this to work.  I had to manually remove the fontawesome icons from my project to get it working.  This could be a more serious issue if you had say 2 addons that were importing fontawesome as there is no nice way to rectify that situation.

**Comment by ynnoj** [comment]
@jackmatt2 I'm working on an enhancement that'll make the import of Font Awesome a user defined config setting, which should prevent this problem in the future. See [#14](https://github.com/Blooie/ember-cli-notifications/pull/14).

**Comment by ynnoj** [comment]
@jackmatt2 I just pushed a [release](https://github.com/Blooie/ember-cli-notifications/releases/tag/v1.1.3) that includes the config setting which should prevent this. Check it out and let me know.
