### ISSUE TITLE
Broken design

### ISSUE THREAD

**Issue by marxsk** [mansona/ember-cli-notifications#188]
Hi,

The last commit (6b4a4dd12b4e1e24967c9ce2ae66e1deb6fb8b58) break existing design. Take a look at https://imagebin.ca/v/3YY3nnF4V406 - screenshot from Chrome.

Previous commit is correct and [x] button is on the right side + tick has different background

**Comment by ynnoj** [comment]
I'm not seeing this unfortunately. Clean install from `master` in a new `ember-cli@2.14.1` app is working perfectly 😕 

Are you able to provide some more details?

**Comment by marxsk** [comment]
I have tried it again (with rm -rf node_modules/ember-cli-notifications) and time to reproduce it properly. But it works.

**Comment by marxsk** [comment]
For those who will encounter such behavior:

local-class was not filled so DIVs did not have proper classes -> solution is to update ember to 2.14.1 as proposed by @ynnoj
