### ISSUE TITLE
ability to replace icon with a custom image

### ISSUE THREAD

**Issue by rinoldsimon** [mansona/ember-cli-notifications#199]
currently i'm using linearicons in my application. Is it possible to replace fontawesome icon with linearicons ?

Something like this
```
var ENV = {
  'ember-cli-notifications': {
    includeLinearicons: true
  }
}
```

**Comment by mansona** [comment]
hey @rinoldsimon 👋 we have replaced the font awesome icons with inline SVG https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340

If you could take a look and let me know if that is ok then we can close this issue 👍

**Comment by rinoldsimon** [comment]
that was helpful 😃
