### ISSUE TITLE
Stopping a notification from autoclosing

### ISSUE THREAD

**Issue by jackmatt2** [mansona/ember-cli-notifications#20]
It would be good if when hovering your mouse over an auto closing notification it would cancel the autoclose functionality and start it again on mouseout.

This would give the user time to read a notification that might have more text than usual.

**Comment by ynnoj** [comment]
Working on this at [feature/hover-pauses-clear](https://github.com/Blooie/ember-cli-notifications/tree/feature/hover-pauses-clear).
