### ISSUE TITLE
Need to fix regression from #2f181d31 (breaks when environment variables not present)

### ISSUE THREAD

**Issue by jacobq** [mansona/ember-cli-notifications#202]
Commit https://github.com/stonecircle/ember-cli-notifications/commit/2f181d31d3d4d1b498900f398aebeda085f773de introduces a rather nasty regression wherein users will encounter an error (`Error: Assertion Failed: Cannot call get with 'clearDuration' on an undefined object`) unless they define `ember-cli-notifications` settings in their application's configuration. e.g.
```javascript
// config/environment.js
...
    const ENV = {
...
        'ember-cli-notifications': {
            // includeFontAwesome: true,
            // autoClear: false,
            // clearDuration: 2400
        },
...
```

The [culprit is here](https://github.com/stonecircle/ember-cli-notifications/commit/2f181d31d3d4d1b498900f398aebeda085f773de#diff-48106eb91c481ba31b7f2bf8cdb486d7R5) where `globals` may be assigned `undefined` meanwhile below it is assumed to be valid when passed to `getWithDefault`.

**Comment by jacobq** [comment]
Note: [this new test](https://github.com/stonecircle/ember-cli-notifications/pull/201/commits/4e6741060327da3a53dad185aa3e6611601aa6fe#diff-49aa7798b202c7090d94239b42145f44R24) fails when [this config](https://github.com/stonecircle/ember-cli-notifications/blob/6b4a4dd12b4e1e24967c9ce2ae66e1deb6fb8b58/tests/dummy/config/environment.js#L26-L29) is removed.

**Comment by jacobq** [comment]
BTW, could someone help me understand why this addon uses two different methods to read options from the environment?
* [`ENV` in component](https://github.com/stonecircle/ember-cli-notifications/blob/master/app/components/notification-message.js#L4)
* [`ember-get-config` in service](https://github.com/stonecircle/ember-cli-notifications/blob/master/addon/services/notification-messages-service.js#L10)

**Comment by jacobq** [comment]
BTW, CI failure appears to be caused by https://github.com/romulomachado/ember-cli-string-helpers/pull/19

**Comment by mansona** [comment]
all of the things you mention here were fixed in https://github.com/stonecircle/ember-cli-notifications/pull/197

let me know if you have any more issues 👍
