### ISSUE TITLE
Can we use svgs instead of Glyphicons / fontawesome ?

### ISSUE THREAD

**Issue by gokatz** [mansona/ember-cli-notifications#204]
Can we use SVGs instead of Glyphicons / fontawesome? I would really love to help on this front!

**Comment by sdhull** [comment]
See #205 and  @mansona's [comment on a different PR](https://github.com/stonecircle/ember-cli-notifications/pull/185#issuecomment-382873190)

Hopefully something for this lands soon, however the author of that PR hasn't responded yet 😕

**Comment by kaermorchen** [comment]
I use [ember-mdi](https://kaermorchen.github.io/ember-mdi/) for icons and I just created a new component `notification-message`

```
//app/pods/components/notification-message/component.js
import NotificationMessage from 'ember-cli-notifications/components/notification-message';
import { computed } from '@ember/object';

export default NotificationMessage.extend({
  notificationIcon: computed('notification.type', function() {
    switch (this.get('notification.type')){
      case 'info':
        return 'information-variant';
      case 'success':
        return 'check';
      case 'warning':
        return 'alert-circle-outline';
      case 'error':
        return 'exclamation';
    }
  }),

  closeIcon: 'close',
});
```

```
//app/pods/components/notification-message/template.hbs
<div class="c-notification__icon">
  {{mdi-icon notificationIcon size=20}}
</div>
<div class="c-notification__content">
  {{#if notification.htmlContent}}
    {{{notification.message}}}
  {{else}}
    {{notification.message}}
  {{/if}}
  <div class="c-notification__close" {{action "removeNotification"}} title="Dismiss this notification">
    {{mdi-icon "close" size=20}}
  </div>
</div>
{{#if notification.autoClear}}
  <div class="c-notification__countdown" style={{notificationClearDuration}}></div>
{{/if}}
```
But it broke some styles of the notification-message component

**Comment by mansona** [comment]
Howdy folks 👋 I'm finally closing this issue 🎉 you can check out the new version https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 where we have moved to **only** using SVG icons.

Let me know if there are any issues
