### ISSUE TITLE
Support Font Awesome v5 (https://github.com/FortAwesome/ember-fontawesome)

### ISSUE THREAD

**Issue by mhluska** [mansona/ember-cli-notifications#206]
Is it possible to integrate this with [FortAwesome/ember-fontawesome](https://github.com/FortAwesome/ember-fontawesome)?

**Comment by mansona** [comment]
Hi @mhluska I'm closing this issue because we're actually using SVG directly now for the icons https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340

let me know if you have any questions
