### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [mansona/ember-cli-notifications#207]
After installing ember-cli-notifications in an Ember project, following error appears when running the server:

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
ember-cli-notifications Version: 4.2.1
### Steps to Reproduce
In the Ember project install ember-cli-notifications:

> ember install ember-cli-notifications

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by rudymacias** [comment]
I get the same deprecation warnings.

Ember Version: 3.0.0
Ember CLI Version: 3.0.2
ember-cli-notifications Version: 4.2.1

**Comment by mansona** [comment]
I'm pretty sure this has been fixed due to our upgrade on https://github.com/stonecircle/ember-cli-notifications/pull/197 so please let me know if it's still an issue 👍
