### ISSUE TITLE
Error: did not pass the parameters required for generating its dynamic segments error after upgrading 4.3.1

### ISSUE THREAD

**Issue by ahmetemrekilinc** [mansona/ember-cli-notifications#208]
Hello, after updaring my ember-ci-notifications addon in my project from 4.2.1 to 4.3.1 I started to get following error in some of link-to helpers.
`Assertion Failed: You attempted to define a `{{link-to "component-list.custom-module-route"}}` but did not pass the parameters required for generating its dynamic segments. this.get(...).setDefaultAutoClear is not a function`
This might be related to the new addons that are integrated after 4.2.1.

**Comment by ahmetemrekilinc** [comment]
I found the reason for this issue. After deleting following line from my base route, the problem is gone.
`this.get('notifications').setDefaultAutoClear(true);`
As a result, setDefaultAutoClear usage can be deleted from the documentation page:
http://stonecircle.github.io/ember-cli-notifications/

**Comment by konradjurk** [comment]
Ran into the same problem. Figured out in these lines
https://github.com/stonecircle/ember-cli-notifications/blob/97ff4860407f02a9232063580b9d02f87ba577be/addon/services/notification-messages-service.js#L10
https://github.com/stonecircle/ember-cli-notifications/blob/97ff4860407f02a9232063580b9d02f87ba577be/addon/services/notification-messages-service.js#L25
that it now picks the default values from the `ENV.ember-cli-notifications` object in your `environment.js` and the corresponding functions are dead. Good change, just not yet documented.
