### ISSUE TITLE
setDefaultClearDuration is missing in latest release

### ISSUE THREAD

**Issue by Kilowhisky** [mansona/ember-cli-notifications#211]
Seems like the method `setDefaultClearDuration` is no longer available on the service. The documentation still states that it is present.  This occurred sometime between 4.2.1 and 4.3.1.

**Comment by mansona** [comment]
@Kilowhisky thanks for the issue report 👍 

This was fixed in 4.3.2 https://github.com/stonecircle/ember-cli-notifications/pull/209 🎉

**Comment by Kilowhisky** [comment]
That’s autoClear not clearDuration. I tried 4.3.2.

**Comment by mansona** [comment]
Indeed you're right, sorry I misread the function 😞 

I have now fixed this in https://github.com/stonecircle/ember-cli-notifications/pull/213 and published 4.3.3 with the fix
