### ISSUE TITLE
setDefaultClearDuration is missing

### ISSUE THREAD

**Issue by M0untainfox** [mansona/ember-cli-notifications#212]
Hi,
The function `setDefaultClearDuration()`  is no longer available, but it's still referenced in the documentation. Is that an accidental remove ?

**Comment by mansona** [comment]
@M0untainfox thanks for the issue report 👍

This was fixed in 4.3.2 #209 🎉

**Comment by mansona** [comment]
As a result of https://github.com/stonecircle/ember-cli-notifications/issues/211#issuecomment-386287756 I have realised that I misread your issue report.

This has now been fixed in #213 and v4.3.3 has been published 🎉 

sorry for the confusion
