### ISSUE TITLE
Feature: CSS classes for the notification messages

### ISSUE THREAD

**Issue by artemgurzhii** [mansona/ember-cli-notifications#215]
I have found this issue during app acceptance testing.

What I'm trying to test, is that when a certain button is clicked - certain notification is shown, but there are problems achieving this currently.

The feature I propose is to make CSS classes be globally configurable from the `ember-cli-notifications/services/notification-messages-service` service.

Currently, there is an option to configure them through each possible notification message type options.

```js
get(this, 'notifications').success('Yay!!! Message succesfully showed', {
  cssClasses: 'some-custom-class'
});
```

And I can override each method definition with something like this
```js
import Ember from 'ember';
import NotificationsService from 'ember-cli-notifications/services/notification-messages-service';

const {
  merge
} = Ember;

export default NotificationsService.extend({
  error(message, options) {
    options = this._overrideOptions({ options });
    this._super(...arguments);
  },

  success(message, options) {
    options = this._overrideOptions({ options });
    this._super(...arguments);
  },

  // NOTE: All other methods ...
  _overrideOptions({ options = { cssClasses: '' } }) {
    return merge(options, {
      cssClasses: `${options.cssClasses} notification-message`
    });
  }
});

```
Which is not the best option as it is requiring additional code and if new notification method type will be added(except `error, success, info, warning `) - we will need to update it.

But what I'm proposing/want/need is to have the ability to declare one shared class for all of the notifications types:

```js
import NotificationsService from 'ember-cli-notifications/services/notification-messages-service';

export default NotificationsService.extend({
  cssClasses: 'some-css-class'
});
```

or

```js
//  my-app-root/config/environment.js

ENV['ember-cli-notifications'] = {
  messageCssClasses: 'some-longer-css-class'
};
```

or any other solution that will be the best option.

**Comment by mansona** [comment]
hey @artemgurzhii thanks for the issue! I'm trying to understand why you're looking for this feature 🤔 are you just looking to be able to tell in a test what type of message has been displayed? if we use a data test selector (you can read more here: https://github.com/simplabs/ember-test-selectors) along the lines of `data-test-notification-type="error"` would that help? it would mean that you could assert on that data test selector

let me know what you think. Also, we have significantly simplified the class structure now that https://github.com/mansona/ember-cli-notifications/pull/251 has been merged so you might be able to achieve what you're looking for using class selectors 🤔

**Comment by artemgurzhii** [comment]
Hey @mansona , ooh, it was a long time ago so I don't actually remember the original problem I was experiencing, AFAIR it could either some problem with the testing(as you said), or I just may need generic CSS class for all of the notifications.

But anyway, if problem is solved then everything is ok now, thank you! :)

**Comment by mansona** [comment]
So I was doing some debugging and it looks like we already have this functionality 🤔 it looks like we're binding a `data-test` attribute with the notification type already 🎉 https://github.com/mansona/ember-cli-notifications/pull/251/files#diff-4c3d0076344af6f16f6854e48ee0e3adR23

I am going to close this issue for now but if you come across this in the future please feel free to open it up again 👍
