### ISSUE TITLE
autoprefixer is not applied

### ISSUE THREAD

**Issue by lolmaus** [mansona/ember-cli-notifications#22]
Hi!

I can see animations working in the official demo, but in my app they don't.

The reason is the lack of prefixes.

**Comment by lolmaus** [comment]
I'm using `ember-cli-notifications@1.1.3`.

I tried installing `ember-cli-autoprefixer` into my app, but it didn't help.

**Comment by ynnoj** [comment]
@lolmaus Pull the [animation-fix](https://github.com/Blooie/ember-cli-notifications/tree/animation-fix) branch and see if that fixes.

I noticed an issue with the animation names clashing with the interpolated variable name.

**Comment by griffind** [comment]
That fixed my animation problems in Mozzila, still broken in Safari.

**Comment by lolmaus** [comment]
Thank you, @ynnoj. When is this gonna hit npm?

**Comment by ynnoj** [comment]
@lolmaus At some point today, working on an update.
