### ISSUE TITLE
Breaks glimmer template only components

### ISSUE THREAD

**Issue by nickschot** [mansona/ember-cli-notifications#226]
Template only components are currently broken by ember-css-modules < 1.0.0 . There is a 1.0.0-beta.1 available which fixes this.

See:
 - https://github.com/salsify/ember-css-modules/releases
 - https://github.com/salsify/ember-css-modules/issues/98

**Comment by cah-brian-gantzler** [comment]
If I understand correctly, the beta should also fix the following issue

WARNING: /Users/brian.gantzler/source/rxid/ember/ember-rxid/node_modules/ember-css-modules/tests/dummy-addon:
WARNING:    Missing package directory

**Comment by nickschot** [comment]
Greenkeeper made a branch for the new stable ember-css-modules: #228

**Comment by erichaus** [comment]
@ynnoj @mansona any way we could get this dep updated which will resolve the warning message anyone using this is seeing in their project? thanks! (ps checked out Moltin - seems interesting!)
```
WARNING:
WARNING: /Users/eric/Dropbox/projects/sqwok/build/client-web/node_modules/ember-css-modules/tests/dummy-addon:
WARNING:    Missing package directory
WARNING:
WARNING: /Users/eric/Dropbox/projects/sqwok/build/client-web/node_modules/ember-css-modules/tests/dummy-less-addon:
WARNING:    Missing package directory
WARNING:
WARNING: /Users/eric/Dropbox/projects/sqwok/build/client-web/node_modules/ember-css-modules/tests/dummy-sass-addon:
WARNING:    Missing package directory
WARNING:
WARNING: /Users/eric/Dropbox/projects/sqwok/build/client-web/node_modules/simple-html-tokenizer/commands:
WARNING:    Missing package directory
WARNING: For addon at path /Users/eric/Dropbox/projects/sqwok/build/client-web/node_modules/ember-css-modules:
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-sass-addon'
WARNING:    Excluding invalid/malformed/missing addon at relative path 'tests/dummy-less-addon'
WARNING: An ember-addon has attempted to override the core command "test". The core command will be used.
```

**Comment by mansona** [comment]
Can anyone try out the new version https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 and let me know if this is still a problem? 🤔

**Comment by mansona** [comment]
We are no longer using css-modules so this won't be an issue anymore 👍
