### ISSUE TITLE
Documentation link does not work

### ISSUE THREAD

**Issue by firstsano** [mansona/ember-cli-notifications#230]
Getting 404 when visiting the link

**Comment by mansona** [comment]
@ynnoj will need to update it but for now it is available here: http://ynnoj.github.io/ember-cli-notifications/

**Comment by firstsano** [comment]
thanks, should I close the issue, or should I wait until description is fixed?

**Comment by mansona** [comment]
I think we should leave it open until it is fixed 👍 

@ynnoj do you want to do it real quick? Or would you like to add me as an admin collaborator so I can help out with little things like this?

**Comment by ynnoj** [comment]
👋 I've opened #232 to remedy this. @mansona could you take a look? 👀 

Also, I've added you as a collaborator moving forward 👍

**Comment by mansona** [comment]
@ynnoj I've approved that PR there, although there is one more link that can't be changed with a PR. In the Github UI here https://github.com/ynnoj/ember-cli-notifications

Also I don't have permission to edit that one, I think I would need admin rights for that 👍

**Comment by ynnoj** [comment]
@mansona Good spot! Fixed.
