### ISSUE TITLE
Is there an option to remove the icon?

### ISSUE THREAD

**Issue by NullVoxPopuli** [mansona/ember-cli-notifications#233]
![image](https://user-images.githubusercontent.com/199018/49583000-c8ee4f00-f924-11e8-9c5c-83db055e8170.png)

in my styles, I've messed up some things, and teh icon isn't even rendering (using font-awesome 5).
So, since, in my use-case it's just for information, is there a way to configure the removal of the icon?

**Comment by mansona** [comment]
I'm assuming this isn't relevant any more with https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 ? also now that we're not using CSS Modules anymore I assume you could add some CSS to hide it if you wanted in your consuming application? what do you think?

**Comment by NullVoxPopuli** [comment]
I'll try it out tonight!

**Comment by mansona** [comment]
I'm going to close this now that https://github.com/mansona/ember-cli-notifications/pull/251 is merged and I'm pretty sure it will fix your problems 👍 let me know if you need to reopen this issue

**Comment by NullVoxPopuli** [comment]
thanks!
