### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by Fusol13** [mansona/ember-cli-notifications#237]
On ember-cli 2.18.2 those two divs are missing classes. Is there a solution to this?

![chrome_2019-01-17_16-20-32](https://user-images.githubusercontent.com/14942168/51328560-f2e27780-1a73-11e9-9821-62725da4f4fd.png)

**Comment by mansona** [comment]
Hey @Fusol13 thanks for the issue 🎉 

That does seem a bit odd 🤔 could you take a look at the new version and tell me if it has fixed the issue for you https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 thanks 👍

**Comment by mansona** [comment]
I'm pretty sure this will be fixed now that https://github.com/mansona/ember-cli-notifications/pull/251 is merged 👍 I have a feeling that was something to do with css-modules that has now been removed 👍
