### ISSUE TITLE
Memory Leak from ArrayProxy.content

### ISSUE THREAD

**Issue by brandynbennett** [mansona/ember-cli-notifications#238]
Declaring the `content` property on the `notification-messages-service` as an array causes a memory leak. Should be declared as `null` then initialized in `init`. This started happening after I upgraded from Ember 3.5 to 3.7

```
content: null,

  init() {
    set(this, 'content', []);
    this._super(...arguments);
  },
```

**Comment by brandynbennett** [comment]
I tried monkey patching with the above code, but it no longer shows notifications when I do this. It seems setting `content` in init is broken and updates don't get sent to it.

**Comment by erichaus** [comment]
@brandynbennett were you able to figure this out?

**Comment by erichaus** [comment]
I ended up doing this...
```
Service.reopenClass({
  content: null,

  init() {
    // prevent memory leak.
    // https://github.com/ynnoj/ember-cli-notifications/issues/238
    this.set('content', A());
    this._super(...arguments);
  },
});

export default Service.reopen({
  addNotification(options) {
    if (!options.message) throw new Error('missing notification message');
   .....
```

**Comment by mansona** [comment]
@brandynbennett thanks for the report 🎉 

I've moved away from using array proxy in the new version https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 but we are still initialising content in the same way 🤔 does it still cause the memory leak that you're describing? do you have an example of the memory leak?

**Comment by brandynbennett** [comment]
Looks like it's gone now. Thanks!
