### ISSUE TITLE
Clear only notifications of error type

### ISSUE THREAD

**Issue by rinoldsimon** [mansona/ember-cli-notifications#241]
There is an option where we can remove all present notifications before adding a new one using `this.get('notifications').clearAll();`

Is there any option or feature request to clear only notifications of type `error`. For example say something like `this.get('notifications').error.clearAll();` or `this.get('notifications').clearAll('error');`

**Comment by mansona** [comment]
I'm pretty sure you could add this functionality by overriding the service in your app 🤔 would that solve your problem? 

I'm just a little bit reluctant to add a new API for a single use-case, but I want to make sure that people can extend this addon to make it useful for their use-cases as much as possible

**Comment by rinoldsimon** [comment]
Oh, maybe I will give it a try. For now, will close this issue. Thanks
