### ISSUE TITLE
mouseEnter and mouseLeave are deprecated

### ISSUE THREAD

**Issue by jelhan** [mansona/ember-cli-notifications#247]
`mouseEnter` and `mouseLeave` component methods have been deprecated in Ember 3.13. See deprecation guide for details: https://deprecations.emberjs.com/v3.x/#toc_component-mouseenter-leave-move

**Comment by mansona** [comment]
Hey @jelhan thanks for your issue 👍 there has recently been some discussion on https://github.com/mansona/ember-cli-notifications/pull/246 about this issue and hopefully we will have a PR soon that fixes the problem 🎉
