### ISSUE TITLE
override defaults globally

### ISSUE THREAD

**Issue by SirZach** [mansona/ember-cli-notifications#26]
I'd like to globally change the clearDuration to 1200 for every notification in my app in one location. If you agree that this could be useful I could take a crack at submitting a PR for this. Thanks!

**Comment by ynnoj** [comment]
I'm happy to accept a PR for this 👍🏼

**Comment by SirZach** [comment]
i've made some progress on this but not sure how to run the dummy app locally to test it.

EDIT: found the url. just trying to figure out how to write a test for it
