### ISSUE TITLE
production build fails if css minification is enabled

### ISSUE THREAD

**Issue by theenadayalank** [mansona/ember-cli-notifications#260]
Hi @mansona,

I have been using this awesome package for almost three years now. Now the production build is failing after upgrading the `ember-cli-notifications` to `v6.0.0`. I'm attaching screenshots for your reference.

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/17431571/72781573-9813cb00-3c47-11ea-8fe6-ef4bbc0bc2ef.png">

I suspect that the issue arises in the CSS minification part. Here is my CSS minify configuration from `ember-cli-build.js`.

<img width="484" alt="image" src="https://user-images.githubusercontent.com/17431571/72781616-baa5e400-3c47-11ea-856c-347243e15652.png">

After debugging for a while I have found that it works after disabling the `processImport` option in the `ember-cli-build.js` file.

**Comment by mansona** [comment]
Hey @theenadayalank I don't know if you have been following the discussion in #261 and #262 but I think I should have fixed this problem with the latest pre-release.

Cay you try to install the upcoming release using `npm install ember-cli-notifications@next` and let me know if it fixes your problem?

**Comment by mansona** [comment]
I've released the version of ember-cli-notifications `v6.2.0` that fixes this bug. Let me know if you still have any issues 👍
