### ISSUE TITLE
Octane Support?

### ISSUE THREAD

**Issue by Shajansheriff** [mansona/ember-cli-notifications#264]
@mansona  Any plans on upgrading to octane / native class type syntax ?

**Comment by mansona** [comment]
@Shajansheriff what do you mean exactly? there is currently no reason why this wouldn't work with an Octane app so it does already have "Octane Support".

Do you just mean for the internal implementation? if so then we wouldn't be able to support all the way back to Ember 2.18 https://github.com/mansona/ember-cli-notifications/blob/master/.travis.yml#L57 🤔

**Comment by mansona** [comment]
I'm closing this for now 👍 feel free to respond or open this issue again
