### ISSUE TITLE
"on" modifier not working in ember-cli v3.6

### ISSUE THREAD

**Issue by z7ealth** [mansona/ember-cli-notifications#266]
https://github.com/mansona/ember-cli-notifications/blob/1fe3388cb6d3f4245fcf6eb4a7b7d0b6edbbaac1/addon/templates/components/notification-message.hbs#L2

Console Error: on is not a modifier: Helpers may not be used in the element form

**Comment by Shajansheriff** [comment]
@hsduiii Which ember version are you using with?

**Comment by z7ealth** [comment]
> @hsduiii Which ember version are you using with?

Ember 3.6

**Comment by joshuaswift** [comment]
We're getting the same error on Ember 2.18.2 after upgrading to version 6.2.0 of this package.
Any ideas?
Thanks!

**Comment by Shajansheriff** [comment]
@hsduiii I tried it with ember 3.6.1 and it is working fine for me. Can you provide little more information?

@joshuaswift @hsduiii  As far as I know, `{{on}}` modifiers works just fine in ember > 3.11.0 without any polyfill. But if you are < 3.11, please add [ember-on-modifier](https://github.com/buschtoens/ember-on-modifier) polyfill if you haven't. By default ember-cli-notification has the on modifier polyfill, but just try manual installation and do let me know if that works.

**Comment by z7ealth** [comment]
Adding ember-on-modifier solved for me, thanks!

**Comment by joshuaswift** [comment]
Yep solved it for me too 😄 thanks!

**Comment by Shajansheriff** [comment]
@hsduiii @joshuaswift Thanks for your quick reply and Please close the issue if it is solved.
