### ISSUE TITLE
Compile Error on is not a modifier: Helpers may not be used in the element form.

### ISSUE THREAD

**Issue by martinbarilik** [mansona/ember-cli-notifications#282]
Hi, 

i have problem with showing any message at all (using latest version).

ember-cli: 2.18.2
ember-js: 2.18.2

controller: 

```
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';

export default Controller.extend({
    notifications: service(),
    init: function() {
        this.get('notifications').success('helo');
    }
});
```

hbs: 

`  {{notification-container}}`

error: 

```
Uncaught Error: Compile Error on is not a modifier: Helpers may not be used in the element form.
    at runtime.js:3989
    at Compilers.compile (runtime.js:3958)
    at compileStatement (runtime.js:4716)
    at compileStatements (runtime.js:4721)
    at CompilableTemplate.compileStatic (runtime.js:4746)
    at runtime.js:845
    at AppendOpcodes.evaluate (runtime.js:70)
    at VM.next (runtime.js:7246)
    at TemplateIterator.next (runtime.js:7317)
    at RootState.render (renderer.js:60)
```

Any idea what am i doing wrong? Can't figure it out. Thanks for any insight ...

**Comment by cah-brian-gantzler** [comment]
Looks like ember-on-modifier is in devDependancies and should be in dependencies.  

Add https://github.com/ember-polyfills/ember-on-modifier to your applications. You can then also use the on modifier in your application as well.

**Comment by martinbarilik** [comment]
You are right and i am grateful for very quick response.

`npm install ember-on-modifier --save`

fixed the issue.
