### ISSUE TITLE
Issue with using Ember-cli-notification@6.3.0 in a node alpine docker container

### ISSUE THREAD

**Issue by LuisAverhoff** [mansona/ember-cli-notifications#295]
We are using gitlab to test our application and when it comes to our build pipeline, the pipeline fails because this addon is using a npm package called `auto-changelog` that relies on git existing in the environment. Unfortunately, we are using a node-alpine image in our CI pipeline and does not include git. One suggestion from a coworker of mine said that I should include git in the node-alpine image but that would not be ideal. The only solution I see at this moment is to go back to 6.2.0 as that is the latest version that doesn't include `auto-changelog`. Don't know what else could be done about this.

**Comment by mansona** [comment]
whoops 🙈 you're absolutely right! I accidentally added `auto-changelog` to dependencies where it really should have been in devDependencies.

`auto-changelog` is just a tool that is used to generate the CHANGELOG file and really should not have any effect on downstream usage. I'm really sorry for this oversight and thanks for the issue 👍 The fix has been released in v6.3.2
