### ISSUE TITLE
Installation and build failures

### ISSUE THREAD

**Issue by Kilowhisky** [mansona/ember-cli-notifications#31]
I'm trying to install the package with 

`ember install ember-cli-notifications` 

But i'm getting an error 

`The 'ember generate' command requires an entity name to be specified.`

If i install via NPM i get a build fail with the error.

`File not found: \addon.sass`

I see that the file is actually named .scss not .sass.

**Comment by acorncom** [comment]
We're seeing the same issue (Ember-CLI-Notifications, version 1.2.1).  We were seeing the same issue with version 1.1.1, so it almost seems to indicate a different issue (either with our config or with dependencies for this package) ...

**Comment by acorncom** [comment]
Clarification:

> we are seeing the same issue

The issue we're seeing is `File not found: \addon.sass` on an install that was working previously.

Confirmed however that the `'ember generate' command requires` error is coming up on a clean Ember-CLI install with Ember CLI 0.2.3.

We seem to need to run `ember generate ember-cli-notifications` but doing so doesn't fix issues on my end.

**Comment by mansona** [comment]
I'm having a look into this now but from what you mention @Kilowhisky it looks like this is related to an open Ember-Cli bug https://github.com/ember-cli/ember-cli/pull/3846

**Comment by lolmaus** [comment]
I've been using `ember-cli-notifications` in a project, and after upgrading Ember CLI i receive `File not found: \addon.sass`.

My app will no longer start, please help.

**Comment by ynnoj** [comment]
The Sass build issues are fixed in [v1.2.3](https://github.com/Blooie/ember-cli-notifications/releases/tag/v1.2.3).

Closing this as other the install issue is related to https://github.com/ember-cli/ember-cli/pull/3846.
