### ISSUE TITLE
Error loading source map - ember-cli-notifications.css.map 404 (NOT FOUND)

### ISSUE THREAD

**Issue by johnbk** [mansona/ember-cli-notifications#36]
Thanks for the addon.

Just installed 1.2.2, Apart from #31, there seems to be an issue with loading source map.
http://localhost:8000/static/dist/assets/ember-cli-notifications.css.map 404 (NOT FOUND)

Please take a look.
Was googling around and found this - if it helps.
https://github.com/ember-cli/ember-cli/issues/810

**Comment by adrien-desfourneaux** [comment]
Having the same issue. Is it resolved somewhere ?

**Comment by eddiesholl** [comment]
Any ideas floating around for this one?

**Comment by ynnoj** [comment]
As of [4.0.0](https://github.com/stonecircle/ember-cli-notifications/releases/tag/v4.0.0) we're using PostCSS to compile CSS. Sourcemaps _should_ now work out of the box.
