### ISSUE TITLE
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities

### ISSUE THREAD

**Issue by lolmaus** [mansona/ember-cli-notifications#37]
So i receive this warning:

> WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes.

I don't have style bindings in my project, so i searched `node_modules` for someone to blame.

It seems to me that this line is the offender:

https://github.com/Blooie/ember-cli-notifications/blob/master/app/templates/components/notification-message.hbs#L10-10

**Comment by ynnoj** [comment]
What version are you using? I thought I'd fixed this warning with #28.

I'm unable to replicate with latest (1.2.2).

**Comment by ynnoj** [comment]
Closing. Please reopen if issue resurfaces @lolmaus.
