### ISSUE TITLE
Support for Bootstrap icons

### ISSUE THREAD

**Issue by gzurbach** [mansona/ember-cli-notifications#45]
Hey! I'd like to use your addon but I'm not using font-awesome. I'm trying to keep my vendor.\* as small as possible and Bootstrap glyphicons contain 4 very similar icons that could totally be used in place of the font-awesome ones.

The code change should be fairly simple. I think the users could then specify a global option:

``` javascript
var ENV = {
  'ember-cli-notifications': {
    theme: 'bootstrap' // default would be 'font-awesome'
  }
}
```

What do you think? I should be able to send a PR over in the coming days if you like the idea.

**Comment by ynnoj** [comment]
Hey @gzurbach! We'd be happy to accept a PR that added this functionality :+1:

**Comment by gzurbach** [comment]
Awesome, I will work on that very soon.

**Comment by gzurbach** [comment]
Thank you so much for that! I got caught into other things a ran out of time.
