### ISSUE TITLE
{{bind-attr}} back in repo after revert. 

### ISSUE THREAD

**Issue by Kilowhisky** [mansona/ember-cli-notifications#47]
It appears that the {{bind-attr}}  is back in the repo after it was removed previously.

See: https://github.com/Blooie/ember-cli-notifications/blame/master/app/templates/components/notification-message.hbs

 Looks like this revert caused it. 

https://github.com/Blooie/ember-cli-notifications/commit/19209a309370204004fe18f99ef52f1ef01bd9ec

**Comment by ynnoj** [comment]
There'll be a release tonight that'll address this and the issue that forced the revert.

**Comment by ynnoj** [comment]
Fixed with 53ad385e3cd7c0a4a0f99f8aabf6c8706e2b882a, version `2.0.0` published.

There may be [breaking changes](https://github.com/Blooie/ember-cli-notifications#template) in the consuming app.
