### ISSUE TITLE
Location Customization

### ISSUE THREAD

**Issue by shivamsinha15** [mansona/ember-cli-notifications#51]
Hi is there a way to customize the location of the message ?

**Comment by ynnoj** [comment]
I'm not sure I understand the question. Can you please elaborate further?

**Comment by shivamsinha15** [comment]
Sorry this might be a newbie/ stupid question. But is there a way to control the height/width and location where the notification is displayed?

**Comment by ynnoj** [comment]
The positioning is handled by CSS on the `c-notification__container` element in your template. You could easily override it in the CSS of your consuming application. https://github.com/Blooie/ember-cli-notifications/blob/master/addon/styles/_component.scss#L7

I'm going to close this now. Reopen if you have any further questions.
