### ISSUE TITLE
Injecting into a service

### ISSUE THREAD

**Issue by jackmatt2** [mansona/ember-cli-notifications#55]
I need to use this inside a service but the default initializer does not support this.  Can this be changed to also inject into services or is there some reason you don't want this?

**Comment by jackmatt2** [comment]
``` javascript
export default {
  name: 'notification-messages-service',

  initialize: function(container, application) {
    application.register('notification-messages:service', NotificationMessagesService);

    ['controller', 'component', 'route', 'router', 'service'].forEach(function(injectionTarget) {
      application.inject(injectionTarget, 'notifications', 'notification-messages:service');
    });
  }
};
```

**Comment by mansona** [comment]
I don't see why this would be a problem, if you want to create a PR and you can confirm it works then we'll merge and release a new version for you :+1:
