### ISSUE TITLE
Ability to customize color palette

### ISSUE THREAD

**Issue by marcemira** [mansona/ember-cli-notifications#58]
Hello, your addon is awesome! But, my app uses a strict color palette. So Im looking for a way to customize its colors without ending up doing !important on all your classes, on my app css.. Do you think is there a clean way to achieve this? Thanks man

**Comment by IgorKvasn** [comment]
Hi,
I also want to change the color palette, but I think the current implementation is OK.

There is no need to use `!important`, just use more specific selector, such as:

```
.c-notification.c-notification--error{
  background-color: orange;
}
```

Do this for all message types and also do not forget to style the notification icon (CSS class `.c-notification__icon`). 

I guess this is the best (the only?) way to deal with this.

**Comment by arnebit** [comment]
Hi again,

I used @IgorKvasn's variant, too, but since going from 3.3.1 to 4.0.9, the classes attached to the surrounding divs have changed, e.g. to `_c-notification--success_1k7w9i`. Where does the 1k7w9i come from and can I rely on this to still be there in the future?

**Comment by ynnoj** [comment]
Not sure if there is still demand for this functionality, but #124 would solve this. Take a look at let me know what you think 🙃

@marcemira @IgorKvasn @arnebit

**Comment by arnebit** [comment]
Works as described, thank you.

However, I am not sure I prefer this solution. A minor issue is the naming: what if I want my regular notifications in grey and warnings in yellow? "orangeColour: 'yellow', blueColour: 'grey'" looks weird, I think names by purpose would be better ("warnColour", "infoColour").

A bigger issue for me is that I cannot use colour variables defined in my sass/less files and if I want to change my _primaryColor_ (which, for example, is also used for buttons) or _successColor_ (which is also used on some text elements), I have to change it in two places, which will not be obvious to anyone else reading the code.

**Comment by ynnoj** [comment]
@arnebit Great suggestion for the variable names. Happy to change those.

The other comment is trickier to address. It's difficult to cater for every potential preprocessor in this situation, especially from within the scope of the add-on. It's possible with [ember-css-modules](https://github.com/salsify/ember-css-modules#other-preprocessors) that I can compile and emit a `.scss` file. That way you could feasibly `@import` this within your app and override the variables from there. However this is something I need to explore further before recommending it as a solution.

In the meantime, I think this is a nice implementation which will be a part of the [5.0.0](https://github.com/stonecircle/ember-cli-notifications/milestone/1) release 😄

**Comment by rodrigomf24** [comment]
@ynnoj do you know when is the 5.0.0 release going to be released?

**Comment by ynnoj** [comment]
@rodrigomf24 Hopefully over the next couple weeks.

**Comment by sdhull** [comment]
@ynnoj curious what happened to 5.0.0 release... I can't even find the branch...?

**Comment by jacobq** [comment]
Here's a twiddle showing how to override the colors for now:
https://ember-twiddle.com/d9d370002d8cfd07f5f760c20ca148ce?openFiles=styles.app.css%2C

**Comment by mansona** [comment]
This should no longer be an issue now that we're not using css-modules anymore since https://github.com/mansona/ember-cli-notifications/pull/251 was merged 👍 I'm closing this for now and you can let me know if you still have an issue
