### ISSUE TITLE
Ember.inject.service doesn't work with notifications. 

### ISSUE THREAD

**Issue by Kilowhisky** [mansona/ember-cli-notifications#60]
Is the notification service not supposed to be exposed to being manually injected? 

It seems to stem from the service being injected as 'name:type' as opposed to 'type:name'.

**Comment by ebenoist** [comment]
Is this also why I can't mock this service in component tests?

**Comment by ynnoj** [comment]
@Kilowhisky @ebenoist This _should_ be fixed in #84. I'll be doing a new release over the next day or so.
