### ISSUE TITLE
Helper methods to avoid redundant code

### ISSUE THREAD

**Issue by amageed** [mansona/ember-cli-notifications#68]
Nice job with the addon! It would be great if helper methods were added for the different _types_ of notifications (error, info, success, warning). The method signature would really cut down on repetitive code. I could wrap these into my own service, but if this could be supported out of the box that would be even better.

Examples of what I am proposing:

``` javascript
let message = 'Hello, World!';
let options = { autoClear: true, clearDuration: 1200 };

this.notifications.error(message); // default options, message provided, type: 'error'
this.notifications.success(message, options); // options would override defaults
this.notifications.info(message, options);
this.notifications.warning(message, options);
```

One thing to consider would be whether to guard against `options` that include `message` and `type`, or just merge the properties provided.

**Comment by ynnoj** [comment]
@amageed Great suggestion! Happy to take a look at a PR, or will tackle this myself when I have the time.

**Comment by ynnoj** [comment]
@amageed #69

**Comment by amageed** [comment]
@ynnoj awesome, looks good! Thanks for the quick response.

It might be worth mentioning them in the readme before that branch gets merged.
