### ISSUE TITLE
I am a little confused on how to use this add-on.

### ISSUE THREAD

**Issue by griffind** [mansona/ember-cli-notifications#7]
I npm the add-on, but I get the error that it can not find '/node_modules/broccoli-sass'. Does this add-on have dependancies?

If I am required to download broccoli-sass, can anyone point me in the right direction as to how to consume this add-on with it? 

Any tutorial, blog posts, etc. would be great.
I am new to ember-cli, and appreciate the patience.

Thanks.

**Comment by ynnoj** [comment]
Hey @griffind. You're right, this is a package dependency to compile the included SCSS for the message themes.

You can install it by running `ember install:npm broccoli-sass` in your project directory. I should update the README to mention this.

Let me know if you have any further problems.

**Comment by griffind** [comment]
@ynnoj okay just checking. I am still having trouble though, as I have never really used Sass. After installing 'broccoli-sass' I started to get an error at build that 'font-awesome' was already included, so I removed the 'app.import' statements from your index.js. After that, it built, but the messages do not show. Any idea on how to get this running, I am new to this stuff so naturally I have limited experience. 

Any help is greatly appreciated.

**Comment by griffind** [comment]
@ynnoj Okay I got the notification to show, but the css is not being applied. Will begin working on that now, if you have any suggestions on how to do that, that would be great.

Thanks again for your patience.

**Comment by griffind** [comment]
@ynnoj So, I tried to hack away at getting the addon to work all night and have yet to get it to do so. It threw an error that I needed to create an app.scss file so I did so. In the app.scss file, I tried to use @import to import the /styles from the addon, and that also did not work. I tried importing the styles in my brocfile.js, I tried using browserify.js to consume the addon with ES6 sytax, and none of this worked either. 

I can't help but think that I am missing something that is obvious, but I can't think of what it is.

**Comment by ynnoj** [comment]
@griffind The SCSS for the message styles are compiled to `vendor.css` in your projects `dist/assets` directory. Is this being compiled correctly?

Your Ember app should include this CSS file by default. Take a look at `index.html` in your project and see if it's in there.

``` html
<link rel="stylesheet" href="assets/vendor.css">
```

**Comment by griffind** [comment]
@ynnoj It seems like it is compiling to the vendor.css fine. I have shared a git of the problem here: https://github.com/griffind/fixtureTest 

Let me know if you can find what is going wrong.

**Comment by lolmaus** [comment]
I've ran into the same issue.

Selectors containing interopolation, e. g. [`.#{$notification-css-prefix}`](https://github.com/Blooie/ember-cli-notifications/blob/master/addon/styles/_component.scss#L22) are rendered into `vendor.css` as `.false`, `.false-icon`, `.false-content`, etc.

**Comment by lolmaus** [comment]
Okay, the problem was that the variable's value was unquoted. I've filed a PR: #9.

**Comment by ynnoj** [comment]
@griffind That PR should fix your issue. Pull, test and let me know. If it does I'll bump the release.

Thanks @lolmaus.

**Comment by griffind** [comment]
@ynnoj Yup that did the trick! I can't get the animations to work though, so I'll start looking into that when I get home. 

https://github.com/griffind/fixtureTest

Thanks for all help @lolmaus and @ynnoj .
