### ISSUE TITLE
setDefaultAutoClear function not exist

### ISSUE THREAD

**Issue by shopapps** [mansona/ember-cli-notifications#72]
Hi, 

The readme mentions using:

```
this.notifications.setDefaultAutoClear(true);
```

but this errors saying it is not a function (when I try and use it in my controllers init function) and I cant find a reference to it if i search through the src files.

Is there an easy way to default all messages to auto clear, without manually editing the **services/notification-messages-service.js** file?  ( I assume it would be possible to extend this file, but thought i would check this wasn't already taken into account by another means first)

**Comment by ynnoj** [comment]
@shopapps I've yet to publish a npm version with the new function. I'll try get to that tonight.

**Comment by shopapps** [comment]
ahh, ok..  that would be cool, many thanks.

**Comment by shopapps** [comment]
Also, it would be extra handy as I'm struggling on how to extend the addons services/notification-messages-service.js file, ember cli just isn't picking up the file i added to the apps/services folder  (unless im supposed to put the file some where else?)

**Comment by ynnoj** [comment]
@shopapps Just released [v3.1.1](https://github.com/stonecircle/ember-cli-notifications/releases/tag/v3.1.1), that function should be available now :rocket:
