### ISSUE TITLE
Ability to turn off vendor scss

### ISSUE THREAD

**Issue by netes** [mansona/ember-cli-notifications#76]
Hey,
First of all, thanks for the great addon :)
I've got a question if there's a possibility to turn off vendor styles? I want to write them by myself, but overriding every single selector is a pain :(

**Comment by gentlefox** [comment]
styles/addon.scss
`@after-modue`  should be `@after-module`.

Was hoping to have a fork available for you that includes styling as an optional .scss file. I'll take another look at this tonight after work.

**Comment by mansona** [comment]
@gentlefox that typo is now fixed btw 👍

**Comment by mansona** [comment]
We have moved away from SCSS now and vastly simplified the css stack now that https://github.com/mansona/ember-cli-notifications/pull/251 has been merged. I am going to close this for now but please let me know if you want to open it again 👍
