### ISSUE TITLE
use in component integration tests

### ISSUE THREAD

**Issue by maartenparmentier** [mansona/ember-cli-notifications#80]
Hi! Thanks for this great library.

I want to use this library in my component integration tests, but I'm not sure how exactly... ?

```
import notifications from 'appName/initializers/notifications';

moduleForComponent('x-send-message', 'Integration | Component | x-send-message', {
   integration: true,
  setup() {
     notifications.initialize(this)
     manualSetup(this.container);
   }
 });    
```

the problem with this approach is that application context in this integration test doesn't have an `inject` method, but this library wants to `application.inject(injectionTarget, 'notifications', 'notification-messages:service');` so that can't work.

Any suggestions on how I can use this library in an integration test?

**Comment by mansona** [comment]
@maartenparmentier to be honest no i don't know how to use this in an integration test 😖  If you have any ideas or anything you think we should look into any help would be appreciated
