### ISSUE TITLE
DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead.

### ISSUE THREAD

**Issue by andrei-sheina** [mansona/ember-cli-notifications#88]
DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge] See http://emberjs.com/deprecations/v2.x/#toc_ember-merge for more details.

Triggered here - https://github.com/stonecircle/ember-cli-notifications/blob/master/addon/services/notification-messages-service.js

**Comment by ynnoj** [comment]
Fixed in #84.
