### ISSUE TITLE
Styles not being imported

### ISSUE THREAD

**Issue by shawjak3** [mansona/ember-cli-notifications#94]
Just installed this and I see the notification but the styles are all missing. If I copy the styles from `basscss`, `basscss-colors`, and `basscss-background-colors` into my own stylesheet the notifications work. But I also see another issue where the `/* Base */
.c-notification__container` in `addon/styles/components/notification-container.css` isn't working because the css attributes for this rule aren't being applied, `.c-notification__container`. Please let me know if I missed a step or if something is off with the addon.

**Comment by cimtico** [comment]
I just encountered this issue also.

**Comment by ynnoj** [comment]
Hey, sorry about the troubles! I just released `4.0.6` which should fix this issue.

Let me know how it works out for you.

**Comment by cimtico** [comment]
Thank you for the quick solution :+1:

**Comment by shawjak3** [comment]
Awesome, it works great now. Thanks for the great add on and quick response!

**Comment by cimtico** [comment]
It seems styles are being loaded, however all I get are white boxes. Am I missing something?
I added https://github.com/salsify/ember-css-modules but that didn't seem to help.
I am also using sass and materializecss

**Comment by shawjak3** [comment]
@cimtico I am just using sass and mine works fine. I dont have `ember-css-modules` or `materializecss` on my setup. I did have to restart the ember server a couple times and then they started working. Only other thing is to make sure it updated your `package.json` with the right version. Sorry if I'm no help.

**Comment by cimtico** [comment]
Nevermind. it seems materializecss has a styling called white that sets background-color: #FFFFFF !important;
I hate when styles use important :(

**Comment by bartam** [comment]
I'm getting the same error when running with --environment="production".  Works with without it.  Any ideas?

**Comment by ynnoj** [comment]
@bartam Please track at #146. Will be fixed this evening 🙃
